### ISSUE TITLE
Alternatives and alike waidps?

### ISSUE THREAD

**Issue by MiChaelinzo** [samiux/waidps#2]
Are there any open-software alike this one? waidps is not relevant anymore? wireshark is hard to read for any deauth etc.

**Comment by samiux** [comment]
According to my knowledge, there is no attack surface for WPA3 even the client is WPA2 that under WPA3 enabled device.

**Comment by MiChaelinzo** [comment]
Oh that sucks it means modern and newest model are more vulnerable to deauth, handshakes, eviltwin, & ddos etc.
